sudo: false

os:
  - osx
  - linux

language: node_js
node_js: lts/*

env:
  # travis encrypt "CHAT_WEBHOOK_PATH=\"/v1/xxx\""
  global:
    - secure: "dmD7OM5ermyaTZCdXoTQ7DLD79giKtjDR66ZblH3pgZKc5mweTjYaNOEqVTP9lwzgV1vAcbprnj4JEHP+uepf8qhXMQEd5wEgmKnctF1YvaPNGY32CwWcMsqvK9Uh9W2ODh3G+KxEC7g5tBV/LQb4BSmccwoR09MJ08pu64mH/AJanjhvQEZjv7gu4AP+GMUClQyV4Zcl2FEn386V1yGmg9LMzvGC0gL8wYRTzb4STRDjBQ63I/WpWus/CsGhHt5l54ROpO18l+XiObbI3/tRpcfV+4Uyiz9waqCE4oRze1eQ8RZDXVHXTpd/bFXHPoRI4+NmtJeHyZtup8TUDkaGhOwwPa13reqAQZq5lnFutEUNneH5Xl3u+NQCdA1XVWvra9E7tFn0FLgNjvRk6aAYFUWH7+rEijBmzcFQfkwEN0cs3TY+oUhIt89YvhSwPDl5pU7z/Ug+vuM48YEGOfhKum9zm9d3rT1lhoe/ExcoQTedG+KBv4Meww7vTzk2fexBUvBDXlxE3b2/SVNNl0C/ZUCvqElnLwWgg4JUbnLc+wKgPtXZ5gQMbSte2ykTK70J+S+pBDhbmBXYFqbTSyCkJtlU4GNq6vTlNvFNRQJARm9viKmkLUkHQbVICslZamzfhSzC71GWGC2rrYKuzIvhMdq/FAQcyocg8QBIpnA0is="
    - secure: "vvkQ6iC8swespmWvSaqaY+6QJa81I5KjxF9WSAkH6MkX9DzWbpV9WwusPUCgufbWMbzo5Syx4CrhCYFZE9FjoGHXAt4JrjRdo3SRobUy4ZU4/kYP5oGVHy5XQOPLZKK6F7DGFuUHTOaOFtM5wgvBIk0HHWzuB7M/MKJoGYMSPzcndwYNOclOVdFd4lyI/nguxaskOUy00d/CQXhWZhc0McZQoRW66Vnh4G0CeBdeEnykyO72Bn1W9LcGFV8Wdmg1fXX7EZ6PXAd37ImnM0xDP0b1twWtpACg3sTHhvFmcNX7cn2dv/ELyhl0lruw4EX5LHY+BNkHWnmfhbGLihq+EB1CTRbYUCyE1x1UksDqOLIi6h3X5Qx6XX+Hk2+hgLe4uvpH8i4ugf9fM9DOY8Uo115D9UgAqP4L83yi2oDFqQALp0ZBn4BlfWVjQ09WIlGD+9oD+4Ekde0o663HG/hQ4McXvBV6EKrFNiPJ+BHXD7dcO3WENdvVrUnFt3gbe95vZcObwNlZGRSFez+3fF2nrK2yXjcJH5DtT0RX62i0p4JT3qRJDYyrBkR/f/soXIBUF+94/g/9eMtfofo1jPASWdCjdDALnpxiqtZXVHQPc41WINyZJ11dNnrBIel82nPchLIIg5xcMex6qTS0jg/d6ogoBmBs2HkhxgHIBWARMFE="
addons:
  apt:
    packages:
      - libsecret-1-dev
      - libstdc++6

before_install:
  - export TRAVIS_COMMIT_AUTHOR="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then
      export DART_OS=macos;
    else
      export DART_OS=linux;
    fi
  - curl https://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-$DART_OS-x64-release.zip > dart-sdk.zip
  - curl https://storage.googleapis.com/dart-archive/channels/dev/release/latest/sdk/dartsdk-$DART_OS-x64-release.zip > dart-sdk-dev.zip
  - unzip dart-sdk.zip > /dev/null
  - unzip dart-sdk-dev.zip -d dev > /dev/null
  - git clone -b beta https://github.com/flutter/flutter.git
  - cd flutter
  - git worktree add ../dev/flutter origin/master
  - cd ..
  - export PATH_STABLE=`pwd`/dart-sdk/bin:`pwd`/flutter/bin
  - export PATH_UNSTABLE=`pwd`/dev/dart-sdk/bin:`pwd`/dev/flutter/bin
  - flutter/bin/flutter config --no-analytics
  - export ELECTRON_NO_ATTACH_CONSOLE=1
  - dart-sdk/bin/dart --version
  - flutter/bin/flutter --version
  - dev/dart-sdk/bin/dart --version
  - dev/flutter/bin/flutter --version
  - node --version
  - npm --version

install:
  - npm install --depth 0

script:
  - npm run vscode:prepublish
  - npm run lint
  - npm test

after_script:
  - npm run send_coverage
  - npm run post_result_to_chat
